# Generated by Django 3.2.12 on 2022-07-10 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myCart_App', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAtribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myCart_App.product')),
            ],
        ),
    ]
